# Generated by Django 3.2.5 on 2022-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_yearofpassing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='yearOfpassing',
            field=models.IntegerField(default=2022),
        ),
    ]
