# Generated by Django 3.1.4 on 2022-01-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementPosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comapanyName',
            new_name='companyName',
        ),
    ]
