# Generated by Django 3.1.4 on 2022-01-03 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placementPosts', '0002_auto_20220103_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lastDateToApply',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
