# Generated by Django 3.2.5 on 2022-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementPosts', '0003_auto_20220103_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='yearOfpassing',
            field=models.IntegerField(default=2022),
        ),
    ]
